name: GCC Auto Release

on:
  workflow_dispatch:

jobs:
  check-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Step 1: Kiểm tra phiên bản
      - name: Get latest GCC version
        id: latest_version
        run: |
          latest=$(curl -s https://gcc.gnu.org/releases.html | grep -oP 'GCC \K[0-9]+\.[0-9]+\.[0-9]+' | head -1)
          echo "latest=$latest" >> $GITHUB_ENV

      - name: Get current release version
        id: current_version
        run: |
          current=$(gh release list --limit 1 | awk '{print $1}' | grep -oP '[0-9]+\.[0-9]+\.[0-9]+')
          echo "current=$current" >> $GITHUB_ENV

      - name: Skip if already released
        if: ${{ env.latest == env.current }}
        run: echo "Latest GCC already released. Skipping."

      - name: Continue if new version
        if: ${{ env.latest != env.current }}
        run: |
          echo 'New GCC version found: ${{ env.latest }}'

      # Step 2: Tạo branch mới
      - name: Create new branch
        if: ${{ env.latest != env.current }}
        run: |
          git checkout -b gcc-${{ env.latest }}
          git push origin gcc-${{ env.latest }}

      # Step 3: Build GCC (placeholder)
      - name: Build GCC
        if: ${{ env.latest != env.current }}
        run: |
          echo "Run your build commands here"
          # ./configure && make -j$(nproc)

      # Step 4: Create release
      - name: Create GitHub Release
        if: ${{ env.latest != env.current }}
        uses: actions/create-release@v1
        with:
          tag_name: gcc-${{ env.latest }}
          release_name: GCC ${{ env.latest }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
