name: CCBBR For GCC
run-name: building for GCC
on: 
  schedule:
    - cron: '0 17 * * *'
  workflow_dispatch:
jobs:
  Build-gcc:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses:  actions/checkout@v3
        with:
          path: myrepo
        
      - name: Check built version
        run: echo "gcc_latest=$(git ls-remote --refs https://https://github.com/bo2013/builds.git 'refs/heads/releases/gcc-*' | awk -F'/' '{print $NF}' | sort -V | tail -1)" >> $GITHUB_ENV
        working-directory: ${{ github.workspace }}/myrepo
        
      - name: Check GCC version
        run: |
          echo "gcc_latest=$(git ls-remote --refs https://gcc.gnu.org/git/gcc.git 'refs/heads/releases/gcc-*' | awk -F'/' '{print $NF}' | sort -V | tail -1)" >> $GITHUB_ENV

      - name: install build tools
        run: sudo apt update && sudo apt install build-essential libgmp-dev libmpfr-dev libmpc-dev libisl-dev

      - name: Log versions
        run: |
          echo "my: ${{ env.my_latest }}"
          echo "GCC: ${{ env.gcc_latest }}"
          
      - name: Build
        if: ${{ env.gcc_latest != env.my_latest }}
        run: ./configure && make -j$(nproc) && make install
        working-directory: ${{ github.workspace }}/gcc/
