name: test an code
run-name: ${{ secrets.GITHUB_TOKEN }}
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Check GCC version
        id: gcc_ver
        run: |
          ver=$(git ls-remote --refs https://gcc.gnu.org/git/gcc.git 'refs/heads/releases/gcc-*' | awk -F'/' '{print $NF}' | sort -V | tail -1)
          echo "::set-output name=ver::$ver"

      - name: Check my version
        id: my_ver
        run: |
          ver=$(git ls-remote --refs https://github.com/bo2013/builds.git 'refs/heads/releases/gcc-*' | awk -F'/' '{print $NF}' | sort -V | tail -1)
          echo "::set-output name=ver::$ver"

      - name: Build GCC
        if: ${{ steps.gcc_ver.outputs.ver != steps.my_ver.outputs.ver }}
        run: echo "ok" # build commands
