name: test an code
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-lastest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          path: myrepo

      - name: add a file
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout -B test-branch
          touch hello.txt
          git add hello.txt
          git commit -m "Test commit"
          git push -u origin test-branch
